name: Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch
jobs:
  name: test_job
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run:  npm ci
    - name: Run Lint
      run: npm run lint
    - name: Run Tests
      run: npm test
    - name: Build
      run: npm run build
    - name: Deploy code
      run: echo "Deploying code..."